services:
  testing:
    build:
      context: .
      dockerfile: ./dockerfile.testing
      tags:
        - testing

  development:
    build:
      context: .
      dockerfile: ./dockerfile.development
      tags:
        - development
    ports:
      - 5173:5173
    network_mode: "host"

  production:
    build:
      context: .
      dockerfile: ./dockerfile.production
      tags:
        - production
    ports:
      - 3000:3000
    network_mode: "host"