# syntax=docker/dockerfile:1

FROM node:22-alpine

WORKDIR /src/app/

COPY ./vitest.config.ts /src/app/vitest.config.ts
COPY ./vite.config.ts /src/app/vite.config.ts
COPY ./tsconfig.vitest.json /src/app/tsconfig.vitest.json
COPY ./tsconfig.node.json /src/app/tsconfig.node.json
COPY ./tsconfig.json /src/app/tsconfig.json
COPY ./tsconfig.app.json /src/app/tsconfig.app.json
COPY ./package.json /src/app/package.json
COPY ./index.html /src/app/index.html
COPY ./env.d.ts /src/app/env.d.ts
COPY ./src/ /src/app/src/
COPY ./public/ /src/app/public/

RUN npm install

CMD npm run test
